# Session 3 - Assignment

# Task 1

# Question 1 - Write a function to compute 5/0 and use try/except to catch the exceptions.

In [24]:
def div(n1, n2):
    
    try:
        Result = n1/n2
        print("Output is " +str(Result))
        
    except ZeroDivisionError as e:
        print("Exception...!!!"+str(e))
    
    finally:
        if(n2 == 0):
            print("0 cannot be used as denominator. Try with another number...")
            
n1 = int(input("Enter The Number 1 : " + " "))
n2 = int(input("Enter The Number 2 : " + " "))
div(n1, n2)

Enter The Number 1 :  5
Enter The Number 2 :  0
Exception...!!!division by zero
0 cannot be used as denominator. Try with another number...


# Question 2
# Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

### Hint: Subject,Verb and Object should be declared in the program as shown below.

#### subjects=["Americans ","Indians"]
#### verbs=["play","watch"]
#### objects=["Baseball","Cricket"]

## Output should come as below:
### Americans play Baseball.
### Americans play Cricket.
### Americans watch Baseball.
### Americans watch Cricket.
### Indians play Baseball.
### Indians play Cricket.
### Indians watch Baseball.
### Indians watch Cricket.

In [25]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

#for s in subjects:
 #   for t in verbs:
  #      for u in objects:
   #         print (s,t,u)

output = [(s+"  "+t+"  "+u) for s in subjects for t in verbs for u in objects]
for out in output:
    print (out)

Americans  play  Baseball
Americans  play  Cricket
Americans  watch  Baseball
Americans  watch  Cricket
Indians  play  Baseball
Indians  play  Cricket
Indians  watch  Baseball
Indians  watch  Cricket


# Task 2:
### Question 1. Write a function so that the columns of the output matrix are powers of the input vector.
### The order of the powers is determined by the increasing boolean argument. Specifically, when
### increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [26]:
import numpy as np

def my_vander(p, s=None, increasing = False):
    if increasing == False:
        return (np.column_stack([p**(s - j - 1) for j in range(s)]))
    else:
        return (np.column_stack([p**(j) for j in range(0,s)]))
p=np.array([1,2,3,8])
s=3
print ("Decreasing")
print (my_vander(p,s,False))
print ("Increasing")
print (my_vander(p,s,True))

Decreasing
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [64  8  1]]
Increasing
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  8 64]]
